### ISSUE TITLE
support decimal numbers with leading zeros

### ISSUE THREAD

**Issue by neochrome** [nurpax/c64jasm#55]
Specifying decimal numbers with a leading zero gives a syntax error:

> Syntax error: Expected "!=", "%", "&", "&&", "(", "*", "+", "-", ".", "/", ";", "<", "<<", "<=", "==", ">", ">=", ">>", "[", "\n", "^", "e", "|", "||", or end of input but "1" found.

While binary and hexadecimal allows it.
Mininal example:
```asm
sta #%01
sta #$01
sta #0
sta #01 ; <--- this gives the error
```

**Comment by nurpax** [comment]
I’d prefer not to support this as leading zeros before decimals in C are the octal number syntax. I don’t plan on supporting these and thought better reject them in syntax.

**Comment by neochrome** [comment]
ahh, cool. Thought I should mention it in case it was unintentional :)

**Comment by nurpax** [comment]
Cool..  My disassembler may actually confusingly generate these.. there is a bug in it that immediate fields like "LDA #01" are missing the $ sign, should be "LDA #$01"
