### ISSUE TITLE
Support for windows line endings

### ISSUE THREAD

**Issue by belab** [nurpax/c64jasm#61]
After creating a new file in VS code the assembler always complains about unexpected '\r' at end of lines. It would be nice, if c64jasm could support also different line endings than '\n'

**Comment by belab** [comment]
Right now I'm fine with the following workaround in my settings.json:
`    "[asm]":{
        "files.eol": "\n"
    },`

**Comment by nurpax** [comment]
Thanks for reporting this!

Funny that I never ran into this.  But I guess that's because I've almost exclusively used c64jasm on macOS or Linux.  Should be easy to fix.

**Comment by nurpax** [comment]
This should be fixed in c64jasm 0.8.0.  Just pushed it to npm.

Please reopen if it didn't work for you.  I only tested this on Linux but I don't see why it wouldn't work on Windows now.

**Comment by belab** [comment]
Thanks for fixing it so quickly. I can confirm, it's working now.
