### ISSUE TITLE
[improvement] Support cycle count estimation in disassembly

### ISSUE THREAD

**Issue by shazz** [nurpax/c64jasm#72]
It would be great if in the disassembly, an estimation of the cycles consumed could be added.

A little like in the Stella disassembly:

![image](https://user-images.githubusercontent.com/604708/96800294-f5090100-13d2-11eb-8c14-2d65d0164768.png)

Some existing js 6502 simulator source code:

- https://github.com/skilldrick/6502js
- https://github.com/DrGoldfire/MOS6502.js
- https://github.com/kkasson/6502
- https://github.com/xDonny/6502-Emulator

I'll try to test them to see how good they are

**Comment by shazz** [comment]
I did a little prototype using https://github.com/afeique/MOS6502.js
Easy to integrate, there is only 2 callbacks to add to the disassembler:

````javascript
// This function should return the byte at the specified memory address.
mem_read(address);

// This function should write the specified byte to the specified address.
mem_write(address, value);
````

then calling `run_instruction()` on the simulator will execute on instruction and give the number of cycles consumed.

But I had some issue to map the address read by the simulator and the disassembler byte buffer (`this.buf`).

So finally I only used timing per opcode table.

**Comment by nurpax** [comment]
This could be closed -- @shazz's code is merged.  But thinking about this: perhaps disasm should show conditional cycles like in the above screenshot for the `bne` instructions (2 if branch not taken, 3 if taken)?

**Comment by shazz** [comment]
Maybe just add 2/3 is enough

**Comment by nurpax** [comment]
Yeah, that's what I intended.  

I'll do this.

**Comment by nurpax** [comment]
done in ebde48104a73421e7b65a83b4795a842938e22d3

it's possible to be slightly more precise with the cycle counts.  it's possible to check for page crossing when disassembling branches -- I'm going to fix this too at some point.  Not today though.

**Comment by nurpax** [comment]
all done here 478e07bec06e2f2525cd252d6203f1b5bb8d4864
