### ISSUE TITLE
[bug] macro and label can't have the same name

### ISSUE THREAD

**Issue by shazz** [nurpax/c64jasm#74]
Example:

````
!macro do_something() {
	lda #1
}

+do_something()

do_something:
    lda #2
````

Error:
````
main.asm:7:1: error: Symbol 'do_something' already defined
````

Maybe this is by design, but doesn't look obvious to me as macro are prefixed by +

**Comment by nurpax** [comment]
I guess I'd go with just not allowing same names for labels, variables and macros in the same scope.  Certainly for example in other language if you'd equate macros with functions, you can't generally have a name that's both a local variable and a function with.

![image](https://user-images.githubusercontent.com/297823/106332770-1a3dc300-6290-11eb-909d-f94d4db256db.png)
![image](https://user-images.githubusercontent.com/297823/106332781-2164d100-6290-11eb-8340-d96197e5c10b.png)

**Comment by nurpax** [comment]
I did have a bug w.r.t macro names.  Fixed.  Symbols with the same name should now always conflict regardless of their type.
