### ISSUE TITLE
[improvement] add support for undocumented 6502 opcodes

### ISSUE THREAD

**Issue by shazz** [nurpax/c64jasm#79]
On my version I already added `sax`. I will add the other ones.

Good reference: https://csdb.dk/release/?id=198357

**Comment by nurpax** [comment]
This should go into the next release.  @shazz was maybe doing this?  Or if you don't have time, I'll get it done at some point.  I'm planning to release c64jasm 0.9 which is has a really long list of cool new stuff.  Would be nice to include this too, as then I'd consider c64jasm pretty complete as far as C64 assemblers go.

**Comment by shazz** [comment]
Yes I'll handle it.

**Comment by nurpax** [comment]
Thank you @shazz for your PR.  We now have 6502 undoc'd opcode support.  I'll be making a release today.
